/**
 * PDF Export Utility
 * Server-side PDF generation using HTML template → buffer
 * Falls back to client-side download if no puppeteer available
 */

export interface PdfColumn {
  key: string;
  label: string;
  width?: string | number;
}

export interface PdfExportOptions {
  title: string;
  subtitle?: string;
  companyName?: string;
  columns: PdfColumn[];
  rows: Record<string, unknown>[];
  locale?: string;
  generatedBy?: string;
}

function escapeHtml(str: unknown): string {
  return String(str ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatDate(locale: string): string {
  return new Date().toLocaleDateString(locale === 'de' ? 'de-DE' : locale === 'en' ? 'en-US' : 'hu-HU', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  });
}

/**
 * Generates an HTML string suitable for PDF rendering.
 */
export function generatePdfHtml(options: PdfExportOptions): string {
  const { title, subtitle, companyName, columns, rows, locale = 'hu', generatedBy } = options;

  const headerRow = columns.map(c => `<th style="padding:8px 12px;text-align:left;border-bottom:2px solid #3b82f6;font-weight:600;color:#1e40af;font-size:11px;text-transform:uppercase;letter-spacing:0.5px;">${escapeHtml(c.label)}</th>`).join('');

  const dataRows = rows.map((row, idx) => {
    const bg = idx % 2 === 0 ? '#ffffff' : '#f8fafc';
    const cells = columns.map(c => `<td style="padding:6px 12px;border-bottom:1px solid #e2e8f0;font-size:12px;color:#334155;">${escapeHtml(row[c.key])}</td>`).join('');
    return `<tr style="background:${bg}">${cells}</tr>`;
  }).join('');

  return `<!DOCTYPE html>
<html lang="${locale}">
<head>
<meta charset="UTF-8">
<style>
  @page { margin: 20mm 15mm; size: A4; }
  body { font-family: 'Segoe UI', Arial, sans-serif; margin: 0; padding: 0; color: #1e293b; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 20px; padding-bottom: 15px; border-bottom: 3px solid #3b82f6; }
  .header-left h1 { margin: 0; font-size: 22px; color: #1e40af; }
  .header-left p { margin: 4px 0 0; font-size: 12px; color: #64748b; }
  .header-right { text-align: right; font-size: 11px; color: #64748b; }
  table { width: 100%; border-collapse: collapse; margin-top: 10px; }
  .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #94a3b8; display: flex; justify-content: space-between; }
</style>
</head>
<body>
<div class="header">
  <div class="header-left">
    <h1>${escapeHtml(title)}</h1>
    ${subtitle ? `<p>${escapeHtml(subtitle)}</p>` : ''}
  </div>
  <div class="header-right">
    ${companyName ? `<strong>${escapeHtml(companyName)}</strong><br>` : ''}
    ${formatDate(locale)}
  </div>
</div>
<table>
  <thead><tr>${headerRow}</tr></thead>
  <tbody>${dataRows}</tbody>
</table>
<div class="footer">
  <span>${escapeHtml(title)} — ${rows.length} ${locale === 'hu' ? 'sor' : locale === 'de' ? 'Zeilen' : 'rows'}</span>
  <span>${generatedBy ? `${locale === 'hu' ? 'Készítette' : locale === 'de' ? 'Erstellt von' : 'Generated by'}: ${escapeHtml(generatedBy)}` : ''} | Ainova Cloud Core</span>
</div>
</body>
</html>`;
}

/**
 * Returns a Response with the HTML as a downloadable .html file (PDF-ready).
 * For real PDF, puppeteer or @react-pdf can be added later.
 */
export function createPdfResponse(options: PdfExportOptions): Response {
  const html = generatePdfHtml(options);
  const fileName = `${options.title.replace(/[^a-zA-Z0-9]/g, '_')}_${new Date().toISOString().slice(0, 10)}.html`;

  return new Response(html, {
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Disposition': `attachment; filename="${fileName}"`,
    },
  });
}
